services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      JWT_SECRET: devsecretchange
      JWT_ALG: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ENABLE_INFERENCE: "false"
      POINTS_PER_VIDEO: 10
      FIRST_UPLOAD_BONUS: 50
      MAX_VIDEO_MB: 50
      DEFAULT_LOCALE: en
      # NVIDIA runtime environment variables (modern GPU control)
      # Use "all" or a comma-separated list of GPU indices (e.g. 0,1) or set at runtime.
      NVIDIA_VISIBLE_DEVICES: all
      # Capabilities needed: compute for CUDA inference, utility for nvidia-smi, video if using NVENC, graphics for Vulkan (Real-ESRGAN/RIFE via ncnn-vulkan)
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video,graphics
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    depends_on:
      - db
    ports:
      - "8040:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  db_data:
