version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lctar
      MYSQL_USER: lctar
      MYSQL_PASSWORD: lctarpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: lctar
      RABBITMQ_DEFAULT_PASS: lctarpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: lctar
      DB_USER: lctar
      DB_PASSWORD: lctarpassword
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://lctar:lctarpassword@rabbitmq:5672/
      MYSQLCLIENT_CFLAGS: "-I/usr/include/mysql"
      MYSQLCLIENT_LDFLAGS: "-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
    depends_on:
      - mysql
      - redis
      - rabbitmq

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
