# Generated by Django 5.2.6 on 2025-09-25 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arb", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
