/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\iceCreams.glb --transform 
Files: .\iceCreams.glb [518.98KB] > C:\Users\Doster\Downloads\Telegram Desktop\iceCreams-transformed.glb [148.35KB] (71%)
*/
import React, { forwardRef, useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const Model = forwardRef((props, ref) => {
  const group = useRef()
  const { scene, animations } = useGLTF('models/iceCreams-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (!ref) return
    if (typeof ref === 'function') ref(group.current)
    else ref.current = group.current
  }, [ref])

  useEffect(() => {
    if (!actions) return
    const actionList = Object.values(actions)
    if (!actionList.length) return
    actionList.forEach(action => {
      action.reset().play()
    })
    return () => {
      actionList.forEach(action => {
        action.stop()
      })
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Cloner1" position={[-0.001, -0.036, 0.002]} rotation={[3.065, 0.751, -3.089]}>
          <group name="Eskimo_0" position={[0.068, -0.014, -0.24]} rotation={[1.809, -0.352, 2.193]}>
            <mesh name="Cube1" geometry={nodes.Cube1.geometry} material={materials['Mat.3']} />
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_1" position={[0.18, -0.014, -0.173]} rotation={[1.952, -0.187, 2.715]}>
            <mesh name="Cube1_1" geometry={nodes.Cube1_1.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_2" position={[0.242, -0.014, -0.06]} rotation={[1.993, 0.02, -3.088]}>
            <mesh name="Cube1_2" geometry={nodes.Cube1_2.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_3" position={[0.237, -0.014, 0.078]} rotation={[1.923, 0.238, -2.563]}>
            <mesh name="Cube1_3" geometry={nodes.Cube1_3.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_4" position={[0.192, -0.014, 0.159]} rotation={[1.815, 0.349, -2.191]}>
            <mesh name="Cube1_4" geometry={nodes.Cube1_4.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_5" position={[0.072, -0.014, 0.239]} rotation={[1.571, 0.422, -1.562]}>
            <mesh name="Cube1_5" geometry={nodes.Cube1_5.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_6" position={[-0.084, -0.014, 0.235]} rotation={[1.309, 0.336, -0.879]}>
            <mesh name="Cube1_6" geometry={nodes.Cube1_6.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_7" position={[-0.152, -0.014, 0.198]} rotation={[1.221, 0.242, -0.572]}>
            <mesh name="Cube1_7" geometry={nodes.Cube1_7.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_7" geometry={nodes.Cube_7.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_8" position={[-0.241, -0.014, 0.066]} rotation={[1.148, -0.011, 0.033]}>
            <mesh name="Cube1_8" geometry={nodes.Cube1_8.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_8" geometry={nodes.Cube_8.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_9" position={[-0.236, -0.014, -0.082]} rotation={[1.222, -0.243, 0.594]}>
            <mesh name="Cube1_9" geometry={nodes.Cube1_9.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_9" geometry={nodes.Cube_9.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_10" position={[-0.171, -0.014, -0.182]} rotation={[1.372, -0.375, 1.078]}>
            <mesh name="Cube1_10" geometry={nodes.Cube1_10.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_10" geometry={nodes.Cube_10.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_11" position={[-0.06, -0.014, -0.242]} rotation={[1.593, -0.422, 1.634]}>
            <mesh name="Cube1_11" geometry={nodes.Cube1_11.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_11" geometry={nodes.Cube_11.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
        </group>
        <group name="Cloner" rotation={[-Math.PI, -0.448, -Math.PI]}>
          <group name="Eskimo_0_1" position={[0.041, -0.014, -0.123]} rotation={[-2.778, 0.923, 0.117]}>
            <mesh name="Cube1_12" geometry={nodes.Cube1_12.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_12" geometry={nodes.Cube_12.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_1_1" position={[0.105, -0.014, -0.076]} rotation={[-1.558, 1.354, -1.172]}>
            <mesh name="Cube1_13" geometry={nodes.Cube1_13.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_13" geometry={nodes.Cube_13.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_2_1" position={[0.13, -0.014, -0.003]} rotation={[-0.368, 0.931, -2.43]}>
            <mesh name="Cube1_14" geometry={nodes.Cube1_14.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_14" geometry={nodes.Cube_14.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_3_1" position={[0.109, -0.014, 0.07]} rotation={[-0.231, 0.358, -2.647]}>
            <mesh name="Cube1_15" geometry={nodes.Cube1_15.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_15" geometry={nodes.Cube_15.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_4_1" position={[0.05, -0.014, 0.12]} rotation={[-0.222, -0.232, -2.781]}>
            <mesh name="Cube1_16" geometry={nodes.Cube1_16.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_16" geometry={nodes.Cube_16.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_5_1" position={[-0.044, -0.014, 0.122]} rotation={[-0.375, -0.944, -3.038]}>
            <mesh name="Cube1_17" geometry={nodes.Cube1_17.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_17" geometry={nodes.Cube_17.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_6_1" position={[-0.099, -0.014, 0.084]} rotation={[-1.257, -1.343, 2.304]}>
            <mesh name="Cube1_18" geometry={nodes.Cube1_18.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_18" geometry={nodes.Cube_18.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_7_1" position={[-0.13, -0.014, 0]} rotation={[-2.784, -0.91, 0.699]}>
            <mesh name="Cube1_19" geometry={nodes.Cube1_19.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_19" geometry={nodes.Cube_19.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_8_1" position={[-0.109, -0.014, -0.071]} rotation={[-2.911, -0.352, 0.493]}>
            <mesh name="Cube1_20" geometry={nodes.Cube1_20.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_20" geometry={nodes.Cube_20.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
          <group name="Eskimo_9_1" position={[-0.043, -0.014, -0.123]} rotation={[-2.916, 0.286, 0.347]}>
            <mesh name="Cube1_21" geometry={nodes.Cube1_21.geometry} material={materials['Mat.3']} />
            <mesh name="Cube_21" geometry={nodes.Cube_21.geometry} material={materials['Mat.4']} position={[0, 0.014, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('./models/iceCreams-transformed.glb')
