/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\singleEskimo.glb --transform 
Files: .\singleEskimo.glb [407.09KB] > C:\Users\Doster\Downloads\Telegram Desktop\singleEskimo-transformed.glb [133.13KB] (67%)
*/
import React, { forwardRef, useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const Model = forwardRef((props, ref) => {
  const group = useRef()
  const { scene, animations } = useGLTF('models/singleEskimo-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (!ref) return
    if (typeof ref === 'function') ref(group.current)
    else ref.current = group.current
  }, [ref])

  useEffect(() => {
    if (!actions) return
    const actionList = Object.values(actions)
    if (!actionList.length) return
    actionList.forEach(action => {
      action.reset().play()
    })
    return () => {
      actionList.forEach(action => {
        action.stop()
      })
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube1.geometry} material={materials['Mat.3']} position={[0, -0.014, 0]} rotation={[0.07, 0.592, -0.333]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Mat.4']} position={[0.004, -0.001, -0.002]} rotation={[0.07, 0.592, -0.333]} />
    </group>
  )
})

useGLTF.preload('./models/singleEskimo-transformed.glb')
