/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Train.glb --transform 
Files: .\Train.glb [204.16KB] > path\Train-transformed.glb [8.46KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/Train-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Train-Mat2'].geometry} material={materials['Mat.2']} position={[0.001, 0.26, 0.014]} />
      <mesh geometry={nodes['Train-Wagon'].geometry} material={materials.Wagon} position={[0.001, 0.26, 0.014]} />
      <mesh geometry={nodes['Train-Wheels'].geometry} material={materials.Wheels} position={[0.001, 0.26, 0.014]} />
    </group>
  )
}

useGLTF.preload('models/Train-transformed.glb')
