/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Train.glb -o src/models/Train.jsx -T 
Files: public/models/Train.glb [8.46KB] > E:\source\repos\LCTAR\frontend\src\models\Train-transformed.glb [8.53KB] (-1%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/Train-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Train-Mat2'].geometry} material={materials['Mat.2']} position={[0.001, 0.26, 0.014]} />
      <mesh geometry={nodes['Train-Wagon'].geometry} material={materials.Wagon} position={[0.001, 0.26, 0.014]} />
      <mesh geometry={nodes['Train-Wheels'].geometry} material={materials.Wheels} position={[0.001, 0.26, 0.014]} />
    </group>
  )
}

useGLTF.preload('models/Train-transformed.glb')
