/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\volk_car.glb --transform 
Files: .\volk_car.glb [2.67MB] > C:\Users\Doster\Downloads\Telegram Desktop\volk_car-transformed.glb [203.18KB] (92%)
*/
import React, { forwardRef, useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const Model = forwardRef((props, ref) => {
  const group = useRef()
  const { scene, animations } = useGLTF('models/volk_car-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (!ref) return
    if (typeof ref === 'function') ref(group.current)
    else ref.current = group.current
  }, [ref])

  useEffect(() => {
    if (!actions) return
    const actionList = Object.values(actions)
    if (!actionList.length) return
    actionList.forEach(action => {
      action.reset().play()
    })
    return () => {
      actionList.forEach(action => {
        action.stop()
      })
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Null">
          <group name="scene">
            <group name="Meshes" scale={0.614}>
              <group name="Sketchfab_model" position={[-0.022, 0.072, 0.101]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="_7c5e2f5638e4de89509ce1edababfd1_fbx" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="RootNode" position={[0, -0.058, 0]}>
                    <group name="Exhaust_pipe" position={[2.434, 0.279, 0.979]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Exhaust_pipe_Exhaust_pipe_0" position={[0, 0, 0.011]}>
                        <mesh name="Exhaust_pipe_Exhaust_pipe_0_1" geometry={nodes.Exhaust_pipe_Exhaust_pipe_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Exhaust_pipe_Exhaust_pipe_2_0" position={[0, 0, 0.011]}>
                        <mesh name="Exhaust_pipe_Exhaust_pipe_2_0_1" geometry={nodes.Exhaust_pipe_Exhaust_pipe_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Awn" position={[1.071, 1.325, -0.018]}>
                      <group name="Awning" position={[-0.205, 0.178, 0.035]} scale={100}>
                        <group name="Awning_Awning_0" position={[0.003, 0.012, 0.005]}>
                          <mesh name="Awning_Awning_0_1" geometry={nodes.Awning_Awning_0_1.geometry} material={materials.PaletteMaterial001} />
                        </group>
                      </group>
                      <group name="Awning_support" position={[-1.71, 2.12, 0.599]} rotation={[0, -0.388, 0]} scale={100}>
                        <group name="Awning_support_Handles_0">
                          <mesh name="Awning_support_Handles_0_1" geometry={nodes.Awning_support_Handles_0_1.geometry} material={materials.PaletteMaterial001} />
                        </group>
                      </group>
                    </group>
                    <group name="Back_wheels" position={[1.548, 0.585, -0.427]} scale={100}>
                      <group name="Back_wheels_Bumper_0" position={[0, 0, -0.006]}>
                        <mesh name="Back_wheels_Bumper_0_1" geometry={nodes.Back_wheels_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Back_wheels_Bumper_2_0" position={[0, 0, -0.006]}>
                        <mesh name="Back_wheels_Bumper_2_0_1" geometry={nodes.Back_wheels_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Back_wheels_Tire_0" position={[0, 0, -0.006]}>
                        <mesh name="Back_wheels_Tire_0_1" geometry={nodes.Back_wheels_Tire_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Front_wheel_1" position={[-1.768, 0.4, 0.477]} scale={100}>
                      <group name="Front_wheel_1_Tire_0" position={[0, 0, 0.005]}>
                        <mesh name="Front_wheel_1_Tire_0_1" geometry={nodes.Front_wheel_1_Tire_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Front_wheel_1_Tire_2_0" position={[0, 0, 0.005]}>
                        <mesh name="Front_wheel_1_Tire_2_0_1" geometry={nodes.Front_wheel_1_Tire_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Front_wheel_1_Bumper_2_0" position={[0, 0, 0.005]}>
                        <mesh name="Front_wheel_1_Bumper_2_0_1" geometry={nodes.Front_wheel_1_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} position={[0, 0, -0.002]} />
                      </group>
                    </group>
                    <group name="Front_wheel_2" position={[-1.768, 0.413, -0.672]} scale={100}>
                      <group name="Front_wheel_2_Bumper_0" position={[0, 0, -0.004]}>
                        <mesh name="Front_wheel_2_Bumper_0_1" geometry={nodes.Front_wheel_2_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Front_wheel_2_Bumper_2_0" position={[0, 0, -0.004]}>
                        <mesh name="Front_wheel_2_Bumper_2_0_1" geometry={nodes.Front_wheel_2_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Front_wheel_2_Tire_0" position={[0, 0, -0.004]}>
                        <mesh name="Front_wheel_2_Tire_0_1" geometry={nodes.Front_wheel_2_Tire_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Back_wheels_001" position={[1.548, 0.579, 0.39]} scale={100}>
                      <group name="Back_wheels_001_Bumper_0" position={[0, 0, 0.006]}>
                        <mesh name="Back_wheels_001_Bumper_0_1" geometry={nodes.Back_wheels_001_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Back_wheels_001_Bumper_2_0" position={[0, 0, 0.006]}>
                        <mesh name="Back_wheels_001_Bumper_2_0_1" geometry={nodes.Back_wheels_001_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Back_wheels_001_Tire_0" position={[0, 0, 0.006]}>
                        <mesh name="Back_wheels_001_Tire_0_1" geometry={nodes.Back_wheels_001_Tire_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Bottom" position={[0, 0.453, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Bottom_Bottom_0">
                        <mesh name="Bottom_Bottom_0_1" geometry={nodes.Bottom_Bottom_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Radiator_grille" position={[-1.464, 1.575, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Radiator_grille_Radiator_grille_0">
                        <mesh name="Radiator_grille_Radiator_grille_0_1" geometry={nodes.Radiator_grille_Radiator_grille_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Front_bumper" position={[-2.593, 0.486, 0.733]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Front_bumper_Bumper_0">
                        <mesh name="Front_bumper_Bumper_0_1" geometry={nodes.Front_bumper_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Front_bumper_Bumper_2_0">
                        <mesh name="Front_bumper_Bumper_2_0_1" geometry={nodes.Front_bumper_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Hood" position={[-1.801, 1.262, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Hood_Bumper_0">
                        <mesh name="Hood_Bumper_0_1" geometry={nodes.Hood_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Hood_Body_0">
                        <mesh name="Hood_Body_0_1" geometry={nodes.Hood_Body_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Hood_Bumper_2_0">
                        <mesh name="Hood_Bumper_2_0_1" geometry={nodes.Hood_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Handles" position={[0.268, 1.339, 0.818]} rotation={[0, -0.035, 0]} scale={100}>
                      <group name="Handles_Handles_0">
                        <mesh name="Handles_Handles_0_1" geometry={nodes.Handles_Handles_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Seats" position={[0.404, 1.301, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Seats_Seats_0">
                        <mesh name="Seats_Seats_0_1" geometry={nodes.Seats_Seats_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Seats_Bumper_2_0">
                        <mesh name="Seats_Bumper_2_0_1" geometry={nodes.Seats_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Body" position={[2.653, 0.761, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={87.803}>
                      <group name="Body_Body_0">
                        <mesh name="Body_Body_0_1" geometry={nodes.Body_Body_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Trunk" position={[2.7, 0.752, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Trunk_Trunk_0">
                        <mesh name="Trunk_Trunk_0_1" geometry={nodes.Trunk_Trunk_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Back_bumper" position={[2.714, 0.517, 0.747]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Back_bumper_Bumper_0">
                        <mesh name="Back_bumper_Bumper_0_1" geometry={nodes.Back_bumper_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Back_bumper_Bumper_2_0">
                        <mesh name="Back_bumper_Bumper_2_0_1" geometry={nodes.Back_bumper_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Panel" position={[-1.801, 1.262, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <group name="Panel_Panel_0">
                        <mesh name="Panel_Panel_0_1" geometry={nodes.Panel_Panel_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Steering" position={[-0.798, 1.232, 0.362]} rotation={[-Math.PI / 2, -0.552, 0]} scale={100}>
                      <group name="Steering_Bumper_2_0">
                        <mesh name="Steering_Bumper_2_0_1" geometry={nodes.Steering_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Steering_Bumper_0">
                        <mesh name="Steering_Bumper_0_1" geometry={nodes.Steering_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Steering_Radiator_grille_0">
                        <mesh name="Steering_Radiator_grille_0_1" geometry={nodes.Steering_Radiator_grille_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Pedals" position={[-0.587, 0.663, 0.542]} rotation={[-Math.PI / 2, -0.294, 0]} scale={100}>
                      <group name="Pedals_Bumper_2_0">
                        <mesh name="Pedals_Bumper_2_0_1" geometry={nodes.Pedals_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Pedals_Bumper_0">
                        <mesh name="Pedals_Bumper_0_1" geometry={nodes.Pedals_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Levers" position={[-0.491, 0.539, 0.421]} rotation={[-Math.PI / 2, 0.195, 0]} scale={26.495}>
                      <group name="Levers_Bumper_0">
                        <mesh name="Levers_Bumper_0_1" geometry={nodes.Levers_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Levers_Bumper_2_0">
                        <mesh name="Levers_Bumper_2_0_1" geometry={nodes.Levers_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Rivets" position={[2.783, 1.149, 0.498]} rotation={[0, 0.244, 0]} scale={100}>
                      <group name="Rivets_Bumper_0">
                        <mesh name="Rivets_Bumper_0_1" geometry={nodes.Rivets_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Ignition" position={[-2.672, 0.492, 0.203]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100}>
                      <group name="Ignition_Bottom_0_2">
                        <mesh name="Ignition_Bottom_0" geometry={nodes.Ignition_Bottom_0.geometry} material={materials.PaletteMaterial001} rotation={[0, 0, -0.023]} />
                      </group>
                    </group>
                    <group name="Antennas__1" position={[-2.484, 1.423, 0.371]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.497, 1.497, 45.959]}>
                      <group name="Antennas__1_Antennas_0">
                        <mesh name="Antennas__1_Antennas_0_1" geometry={nodes.Antennas__1_Antennas_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Emblem" position={[-2.476, 1.563, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={54.912}>
                      <group name="Emblem_Bumper_2_0">
                        <mesh name="Emblem_Bumper_2_0_1" geometry={nodes.Emblem_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Front_frame" position={[-0.866, 1.732, 0.675]} rotation={[-Math.PI / 2, 0.265, 0]} scale={[1.497, 1.497, 45.959]}>
                      <group name="Front_frame_Bumper_0">
                        <mesh name="Front_frame_Bumper_0_1" geometry={nodes.Front_frame_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Headlight" position={[-2.622, 1.484, -0.692]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100}>
                      <group name="Headlight_Bumper_0">
                        <mesh name="Headlight_Bumper_0_1" geometry={nodes.Headlight_Bumper_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Headlight_Bumper_2_0">
                        <mesh name="Headlight_Bumper_2_0_1" geometry={nodes.Headlight_Bumper_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Headlight_support" position={[-2.483, 0.662, -0.692]} rotation={[-Math.PI / 2, 0, 0]} scale={[132.157, 132.157, 302.631]}>
                      <group name="Headlight_support_Bottom_0">
                        <mesh name="Headlight_support_Bottom_0_1" geometry={nodes.Headlight_support_Bottom_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Lamp" position={[-2.65, 1.484, -0.692]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={132.157}>
                      <group name="Lamp_Lamp_0">
                        <mesh name="Lamp_Lamp_0_1" geometry={nodes.Lamp_Lamp_0_1.geometry} material={materials.PaletteMaterial002} />
                      </group>
                    </group>
                    <group name="Ram" position={[-2.572, 0.978, 0]} rotation={[-Math.PI / 2, 1.571, 0]} scale={77.915}>
                      <group name="Ram_Ram_0">
                        <mesh name="Ram_Ram_0_1" geometry={nodes.Ram_Ram_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Brush_1" position={[-0.991, 1.561, 0.363]} rotation={[2.099, 1.334, 1.908]} scale={9.793}>
                      <group name="Brush_1_Hair_0">
                        <mesh name="Brush_1_Hair_0_1" geometry={nodes.Brush_1_Hair_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Brush_1_Brush_1_0">
                        <mesh name="Brush_1_Brush_1_0_1" geometry={nodes.Brush_1_Brush_1_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                    <group name="Brush_2" position={[-0.992, 1.571, -0.325]} rotation={[1.028, 1.308, 2.67]} scale={9.412}>
                      <group name="Brush_2_Hair_0">
                        <mesh name="Brush_2_Hair_0_1" geometry={nodes.Brush_2_Hair_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                      <group name="Brush_2_Brush_2_0">
                        <mesh name="Brush_2_Brush_2_0_1" geometry={nodes.Brush_2_Brush_2_0_1.geometry} material={materials.PaletteMaterial001} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('./models/volk_car-transformed.glb')
