/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 testmodel.glb --transform 
Files: testmodel.glb [96.84MB] > C:\Users\Doster\Downloads\Telegram Desktop\testmodel-transformed.glb [16.69MB] (83%)
Author: MG Rips (https://sketchfab.com/MG_GameRips)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dead-by-daylight-the-animatronic-0db438d8a6bc497eb26922dddb91a8dd
Title: Dead by Daylight - The Animatronic
*/

import React, { useState, useCallback } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/testmodel-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  useAnimations(animations, group) // animations retained for future use

  const [weaponsVisible, setWeaponsVisible] = useState(true)
  const toggleWeapons = useCallback((e) => {
    e.stopPropagation()
    setWeaponsVisible(v => !v)
  }, [])

  return (
    <group ref={group} {...props} dispose={null} onClick={toggleWeapons}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        {/* Body parts */}
        <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.ArmsMat} skeleton={nodes.Object_92.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.ArmsAccMat} skeleton={nodes.Object_93.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.LegsMat} skeleton={nodes.Object_94.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.CorpseMat} skeleton={nodes.Object_95.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.TorsoMat} skeleton={nodes.Object_96.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.HeadMat} skeleton={nodes.Object_98.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.HeadAcc} skeleton={nodes.Object_99.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.CorpseMat} skeleton={nodes.Object_100.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
        {/* Weapons (toggle) */}
        {weaponsVisible && (
          <>
            <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.WeaponMat} skeleton={nodes.Object_102.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
            <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.AltWeaponMat} skeleton={nodes.Object_104.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
          </>
        )}
      </group>
    </group>
  )
}

useGLTF.preload('/testmodel-transformed.glb')
