name: Backend tests (arb)

on:
  push:
    paths:
      - "arb/**"
      - ".github/workflows/backend-tests.yml"
  pull_request:
    paths:
      - "arb/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f arb/requirements.txt ]; then
            pip install -r arb/requirements.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install django
          fi

      - name: Prepare env (optional)
        run: |
          cp -f .env.example .env 2>/dev/null || true
          echo "DJANGO_SECRET_KEY=test_ci_secret" >> .env
          echo "DEBUG=1" >> .env

      - name: Migrate (SQLite, in-memory)
        working-directory: arb
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
          DJANGO_DB_ENGINE: sqlite3
          DJANGO_DB_NAME: ":memory:"
        run: |
          python manage.py migrate --noinput

      - name: Run tests (only arb/arb/tests.py)
        working-directory: arb
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
          DJANGO_DB_ENGINE: sqlite3
          DJANGO_DB_NAME: ":memory:"
        run: |
          # Dotted-path на файл tests.py внутри приложения "arb"
          python manage.py test arb.tests --verbosity=2
