name: Backend tests (arb, pytest)

on:
  push:
    paths:
      - "arb/**"
      - ".github/workflows/backend-tests.yml"
  pull_request:
    paths:
      - "arb/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Если есть pyproject.toml — ставим через Poetry и докидываем pytest-инструменты
      - name: Install deps via Poetry (if present)
        if: hashFiles('pyproject.toml') != ''
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
          pip install celery pytest pytest-django

      # Если Poetry нет — ставим из requirements и докидываем нужное
      - name: Install deps via requirements (fallback)
        if: hashFiles('pyproject.toml') == ''
        run: |
          python -m pip install --upgrade pip
          if [ -f arb/requirements.txt ]; then
            pip install -r arb/requirements.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install celery pytest pytest-django

      - name: Prepare env
        run: |
          cp -f .env.example .env 2>/dev/null || true
          echo "DJANGO_SECRET_KEY=test_ci_secret" >> .env
          echo "DEBUG=1" >> .env

      - name: Run pytest on arb/arb/tests.py
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
          CELERY_BROKER_URL: "memory://"
          CELERY_RESULT_BACKEND: "cache+memory://"
          DJANGO_DB_ENGINE: sqlite3
          DJANGO_DB_NAME: ":memory:"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest -q arb/arb/tests.py --ds=arb.settings -s
