name: CI — Django tests

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (requirements.txt если есть; иначе минимальный набор)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "Django>=4.2,<5" "djangorestframework>=3.14,<4"
          fi

      - name: Run Django tests (arb)
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
        run: |
          python -c "import django,sys; print('Django', django.get_version()); print(sys.path)"
          python arb/manage.py test arb -v 2
