name: CI — Django tests (arb)

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # минимальный набор, чтобы settings.py корректно импортировался
            pip install \
              "Django>=4.2,<5" \
              "djangorestframework>=3.14,<4" \
              "celery>=5,<6" \
              "python-decouple>=3.8,<4" \
              "django-cors-headers>=4,<5"
          fi

      - name: Show Django version
        run: python -c "import django; print('Django', django.get_version())"

      - name: Run tests (arb)
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
          # безопасные дефолты, если decouple запросит переменные
          SECRET_KEY: ci-secret-key
          DEBUG: "0"
          ALLOWED_HOSTS: "*"
        run: |
          # прогоняем все тесты приложения arb (файл arb/arb/tests.py включится)
          python arb/manage.py test arb -v 2
