name: CI — Django tests

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # минимально нужно для твоих тестов
            pip install "Django>=4.2,<5" "djangorestframework>=3.14,<4" "celery>=5,<6"
          fi

      - name: Run Django tests (arb)
        env:
          DJANGO_SETTINGS_MODULE: arb.settings
        run: |
          python arb/manage.py test arb -v 2
